'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { buildConfig, hashConfig } = require('../scripts/balance/config');
const { buildSchedule } = require('../scripts/balance/schedule');
const { hashCanonical } = require('../scripts/balance/canonical');
const { openRun, loadRun, resolveRun, StorageStop, sizeTree, renameAtomic } = require('../scripts/balance/storage');
const fingerprint = { hash: 'fixture', commit: 'fixture', worktree: '', files: [] };
function fixture(t, options = {}) {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'balance-storage-'));
  t.after(() => fs.rmSync(root, { recursive: true, force: true }));
  const config = buildConfig({ mode: 'debug', games: 2, players: 2, seed: 22, output: 'artifacts/gameplay-balance/run' }, fingerprint);
  const store = openRun(config, { root, fingerprint, ...options });
  const schedule = buildSchedule(config);
  const manifest = { configHash: config.configHash, scheduleHash: hashCanonical(schedule), samples: {} };
  store.atomic('config.json', config); store.atomic('schedule.json', schedule); store.atomic('manifest.json', manifest);
  return { root, config, store, schedule, manifest };
}
test('输出保护：专用独立目录、禁止越界/链接/覆盖，恢复核对指纹配置', t => {
  const f = fixture(t);
  for (const p of ['.', 'records/x', 'public/x', 'src/x', 'scripts/x', '.git/x', 'artifacts/gameplay-balance', '../outside', 'artifacts/gameplay-balance/run/nested']) assert.throws(() => resolveRun(p, f.root), /输出/);
  assert.throws(() => openRun(f.config, { root: f.root, fingerprint }), /覆盖/);
  assert.equal(loadRun(f.config.output, { root: f.root, fingerprint }).schedule.length, 2);
  assert.throws(() => loadRun(f.config.output, { root: f.root, fingerprint: { hash: 'changed' } }), /指纹/);
  const other = { ...f.config, reportSeed: 1 }; other.configHash = hashConfig(other);
  assert.throws(() => openRun(other, { root: f.root, fingerprint, resume: true }), /恢复配置/);
  const outside = path.join(f.root, 'records'); fs.mkdirSync(outside);
  const linked = path.join(f.root, 'artifacts/gameplay-balance/linked');
  fs.symlinkSync(outside, linked, process.platform === 'win32' ? 'junction' : 'dir');
  assert.throws(() => resolveRun(linked, f.root), /链接|联接/);
  assert.throws(() => f.store.atomic('../records/evil.json', {}), /越界/);
});
test('原子保存：失败临时文件保留，旧清单不变，结果唯一且来源版本有效', t => {
  let reject = false;
  const f = fixture(t, { beforeRename() { if (reject) throw new Error('injected failure'); } });
  const original = fs.readFileSync(path.join(f.store.dir, 'manifest.json'), 'utf8');
  reject = true;
  assert.throws(() => f.store.atomic('manifest.json', { invalid: true }), /原子保存失败/);
  assert.equal(fs.readFileSync(path.join(f.store.dir, 'manifest.json'), 'utf8'), original);
  assert.equal(fs.readdirSync(f.store.dir).some(n => n.includes('.partial-')), true);
  reject = false;
  const spec = f.schedule[0], result = { ...spec, outcome: 'error', winnerId: null };
  f.store.saveResult(result);
  assert.equal(f.store.results(f.schedule).length, 1);
  assert.throws(() => f.store.saveResult(result), /覆盖/);
  assert.throws(() => f.store.saveResult({ ...result, source: 'controlled' }), /来源/);
  assert.throws(() => f.store.saveResult({ ...result, policyVersion: 'other' }), /版本/);
  assert.throws(() => f.store.saveResult({ ...result, outcome: 'censored', winnerId: 'p0' }), /分类/);
});
test('原子保存：Windows短暂占用有限重试，持续占用保留旧文件和临时证据', t => {
  const f = fixture(t), target = path.join(f.store.dir, 'manifest.json'), temp = path.join(f.store.dir, 'retry.partial');
  const original = fs.readFileSync(target, 'utf8'); fs.writeFileSync(temp, 'replacement\n');
  let attempts = 0, waited = 0;
  renameAtomic(temp, target, { rename(from, to) { if (++attempts <= 2) { const error = new Error('locked'); error.code = 'EPERM'; throw error; } fs.renameSync(from, to); }, pause(ms) { waited += ms; } });
  assert.equal(attempts, 3); assert.equal(waited, 15); assert.equal(fs.readFileSync(target, 'utf8'), 'replacement\n');
  fs.writeFileSync(temp, original); attempts = 0;
  assert.throws(() => renameAtomic(temp, target, { rename() { attempts++; const error = new Error('locked'); error.code = 'EBUSY'; throw error; }, pause() {} }), /locked/);
  assert.equal(attempts, 8); assert.equal(fs.readFileSync(target, 'utf8'), 'replacement\n'); assert.equal(fs.readFileSync(temp, 'utf8'), original);
});
test('分段流水：链式摘要/压缩封闭、检查点不含前缀，损坏与不完整尾分别处理', t => {
  const f = fixture(t, { segmentRecords: 2 }), id = f.schedule[0].sampleId;
  f.store.appendAction(id, { type: 'initial', observations: [1] });
  const position = f.store.appendAction(id, { type: 'action', step: 1 });
  f.store.saveCheckpoint(id, { sampleId: id, configHash: f.config.configHash, position, step: 1, stateHash: 'state' });
  assert.equal(f.store.loadEvidence(id).records.length, 2);
  assert.equal(f.store.checkpoint(id).position.records, 2);
  assert.equal(Object.hasOwn(f.store.checkpoint(id), 'actions'), false);
  const directory = path.join(f.store.dir, `samples/${id}/actions`);
  assert.equal(fs.readdirSync(directory).some(n => n.endsWith('.gz')), true);
  f.store.appendAction(id, { type: 'action', step: 2 });
  const active = path.join(directory, 'segment-000001.jsonl');
  fs.appendFileSync(active, '{"incomplete"');
  const evidence = f.store.loadEvidence(id);
  assert.equal(evidence.records.length, 3); assert.equal(evidence.tails.length, 1);
  const restarted = openRun(f.config, { root: f.root, fingerprint, resume: true });
  restarted.appendAction(id, { type: 'action', step: 3 }); restarted.seal(id);
  assert.equal(restarted.loadEvidence(id).records.length, 4);
  assert.equal(fs.readFileSync(active, 'utf8').endsWith('{"incomplete"'), true);
  const gz = path.join(directory, 'segment-000000.jsonl.gz');
  const broken = fs.readFileSync(gz); broken[broken.length - 1] ^= 1; fs.writeFileSync(gz, broken);
  assert.throws(() => restarted.loadEvidence(id), /摘要/);
});
test('输出预算：容量不足不发起写入，原子峰值与原始证据计入占用', t => {
  const f = fixture(t), before = sizeTree(f.store.dir);
  const limited = openRun(f.config, { root: f.root, fingerprint, resume: true, maxBytes: before + 10 });
  assert.equal(limited.bytes, before);
  assert.throws(() => limited.atomic('large.json', { payload: 'x'.repeat(30) }), e => e instanceof StorageStop && e.code === 'output_budget');
  assert.equal(sizeTree(f.store.dir), before);
  assert.equal(fs.existsSync(path.join(f.store.dir, 'large.json')), false);
  assert.equal(limited.remaining(), 10);
});
test('批次清单：结果先完成可补齐清单，但缺结果/未知样本不能视为完赛', t => {
  const f = fixture(t), { reconcile } = require('../scripts/balance/batch');
  const manifest = { samples: Object.fromEntries(f.schedule.map(s => [s.sampleId, { status: 'unstarted' }])) };
  const result = { ...f.schedule[0], outcome: 'censored', winnerId: null };
  reconcile(manifest, f.schedule, [result]);
  assert.equal(manifest.coverage.started, 1); assert.equal(manifest.coverage.terminated, 1); assert.equal(manifest.coverage.unstarted, 1);
  assert.throws(() => reconcile(manifest, f.schedule, []), /缺少有效结果/);
});
test('计算预算：片段停止不是截断，累计预算跨版本保留且等待不计入', t => {
  const f = fixture(t), { openBudget } = require('../scripts/balance/batch');
  const formal = { ...f.config, source: 'formal', runId: 'formal-a' }; formal.configHash = hashConfig(formal);
  let cpu = 0;
  const budget = openBudget(formal, { root: f.root, cpuNow: () => cpu });
  const start = budget.beginWork(); cpu = 7; budget.endWork(start); budget.flush();
  assert.equal(budget.computeMs, 7);
  // No work interval exists during this simulated wait/suspend.
  cpu = 50; assert.equal(budget.computeMs, 7); budget.close();
  const next = { ...formal, runId: 'formal-b', policyVersion: 'new-version' }; next.configHash = hashConfig(next);
  const resumed = openBudget(next, { root: f.root, cpuNow: () => cpu });
  assert.equal(resumed.computeMs, 7); assert.equal(resumed.runComputeMs, 0);
  const resumedStart = resumed.beginWork(); cpu = 53; resumed.endWork(resumedStart); resumed.close();
  const ledger = JSON.parse(fs.readFileSync(path.join(f.root, 'artifacts/gameplay-balance/formal-budget.json'), 'utf8'));
  assert.equal(ledger.computeMs, 10); assert.equal(Object.keys(ledger.runs).length, 2);
});
test('计算预算：同步执行及落盘时间计入，挂起推定与原墙钟/CPU分别保留', t => {
  const f = fixture(t), { openBudget } = require('../scripts/balance/batch');
  let wall = 0, cpu = 0;
  const budget = openBudget(f.config, { root: f.root, workNow: () => wall, cpuNow: () => cpu });
  const start = budget.beginWork(); wall = 20; cpu = 1; budget.endWork(start);
  assert.equal(budget.computeMs, 20);
  wall += 600000; const afterWait = budget.beginWork(); wall += 600000; cpu++;
  budget.endWork(afterWait); assert.equal(budget.computeMs, 21);
  const ledger = budget.snapshot(); assert.equal(ledger.excludedInactiveGapMs, 599999); assert.equal(ledger.runs[f.config.runId].wallWorkMs, 600020);
  budget.close();
});
test('异常中断：首个策略失败保存异常，停止其他样本，恢复不覆盖旧失败', async t => {
  const { temporaryRun } = require('./helpers/balanceFixtures'), { runBatch } = require('../scripts/balance/batch');
  const f = temporaryRun(t); delete f.config.policyConfigs.neutral; f.config.configHash = hashConfig(f.config);
  const manifest = await runBatch(f.config, f);
  assert.equal(manifest.stopReason, 'first_error'); assert.equal(manifest.coverage.terminated, 1); assert.equal(manifest.coverage.unstarted, 1);
  const store = openRun(f.config, { ...f, resume: true }), schedule = store.read('schedule.json');
  const results = store.results(schedule); assert.equal(results.length, 1); assert.equal(results[0].outcome, 'error'); assert.equal(results[0].observations, null);
  const original = fs.readFileSync(path.join(store.dir, `samples/${results[0].sampleId}/result.json`), 'utf8');
  const resumed = await runBatch(f.config, { ...f, resume: true }); assert.equal(resumed.stopReason, 'previous_error');
  assert.equal(fs.readFileSync(path.join(store.dir, `samples/${results[0].sampleId}/result.json`), 'utf8'), original);
});
test('计算预算：耗尽保存待恢复，不填逻辑截断或胜负，片段轮转仍可续行', async t => {
  const { temporaryRun } = require('./helpers/balanceFixtures'), { runBatch, openBudget } = require('../scripts/balance/batch');
  const f = temporaryRun(t, { limits: { rounds: 3, actions: 100, computeMs: 5 } });
  let cpu = 0;
  const budget = openBudget(f.config, { root: f.root, cpuNow: () => cpu++ });
  // openBudget creates only its own budget directory. Initialize a fresh run in that directory's parent.
  const moved = { ...f.config, output: 'artifacts/gameplay-balance/execute', runId: 'execute' }; moved.configHash = hashConfig(moved);
  const manifest = await runBatch(moved, { ...f, budget });
  assert.equal(manifest.stopReason, 'compute_budget'); assert.equal(manifest.coverage.pending, 1); assert.equal(manifest.coverage.terminated, 0);
  const store = openRun(moved, { ...f, resume: true });
  assert.equal(store.results(store.read('schedule.json')).length, 0);
  const sliced = temporaryRun(t, { limits: { rounds: 3, actions: 100, sliceMs: 0 } });
  const rotated = await runBatch(sliced.config, sliced);
  assert.equal(rotated.status, 'complete', JSON.stringify(rotated)); assert.equal(rotated.coverage.terminated, 2);
});
test('异常中断：恢复检查点篡改保存异常并首错停止，不以待恢复掩盖', async t => {
  const { temporaryRun } = require('./helpers/balanceFixtures'), { runBatch } = require('../scripts/balance/batch');
  const f = temporaryRun(t);
  await runBatch(f.config, { ...f, stopAfterActions: 4 });
  const store = openRun(f.config, { ...f, resume: true }), schedule = store.read('schedule.json'), id = schedule[0].sampleId;
  const checkpoint = store.checkpoint(id); checkpoint.memory.p0 = { forged: true };
  store.saveCheckpoint(id, checkpoint);
  const resumed = await runBatch(f.config, { ...f, resume: true });
  assert.equal(resumed.stopReason, 'first_error', JSON.stringify(resumed));
  assert.equal(resumed.coverage.terminated, 1); assert.equal(resumed.coverage.unstarted, 1);
  assert.equal(store.results(schedule)[0].outcome, 'error');
  assert.match(store.results(schedule)[0].reason, /检查点/);
});
