'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { buildConfig, hashConfig } = require('../scripts/balance/config');
const { buildSchedule } = require('../scripts/balance/schedule');
const { hashCanonical } = require('../scripts/balance/canonical');
const { openRun, loadRun, resolveRun, StorageStop, sizeTree } = require('../scripts/balance/storage');
const fingerprint = { hash: 'fixture', commit: 'fixture', worktree: '', files: [] };
function fixture(t, options = {}) {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'balance-storage-'));
  t.after(() => fs.rmSync(root, { recursive: true, force: true }));
  const config = buildConfig({ mode: 'debug', games: 2, players: 2, seed: 22, output: 'artifacts/gameplay-balance/run' }, fingerprint);
  const store = openRun(config, { root, fingerprint, ...options });
  const schedule = buildSchedule(config);
  const manifest = { configHash: config.configHash, scheduleHash: hashCanonical(schedule), samples: {} };
  store.atomic('config.json', config); store.atomic('schedule.json', schedule); store.atomic('manifest.json', manifest);
  return { root, config, store, schedule, manifest };
}
test('输出保护：专用独立目录、禁止越界/链接/覆盖，恢复核对指纹配置', t => {
  const f = fixture(t);
  for (const p of ['.', 'records/x', 'public/x', 'src/x', 'scripts/x', '.git/x', 'artifacts/gameplay-balance', '../outside', 'artifacts/gameplay-balance/run/nested']) assert.throws(() => resolveRun(p, f.root), /输出/);
  assert.throws(() => openRun(f.config, { root: f.root, fingerprint }), /覆盖/);
  assert.equal(loadRun(f.config.output, { root: f.root, fingerprint }).schedule.length, 2);
  assert.throws(() => loadRun(f.config.output, { root: f.root, fingerprint: { hash: 'changed' } }), /指纹/);
  const other = { ...f.config, reportSeed: 1 }; other.configHash = hashConfig(other);
  assert.throws(() => openRun(other, { root: f.root, fingerprint, resume: true }), /恢复配置/);
  const outside = path.join(f.root, 'records'); fs.mkdirSync(outside);
  const linked = path.join(f.root, 'artifacts/gameplay-balance/linked');
  fs.symlinkSync(outside, linked, process.platform === 'win32' ? 'junction' : 'dir');
  assert.throws(() => resolveRun(linked, f.root), /链接|联接/);
  assert.throws(() => f.store.atomic('../records/evil.json', {}), /越界/);
});
test('原子保存：失败临时文件保留，旧清单不变，结果唯一且来源版本有效', t => {
  let reject = false;
  const f = fixture(t, { beforeRename() { if (reject) throw new Error('injected failure'); } });
  const original = fs.readFileSync(path.join(f.store.dir, 'manifest.json'), 'utf8');
  reject = true;
  assert.throws(() => f.store.atomic('manifest.json', { invalid: true }), /原子保存失败/);
  assert.equal(fs.readFileSync(path.join(f.store.dir, 'manifest.json'), 'utf8'), original);
  assert.equal(fs.readdirSync(f.store.dir).some(n => n.includes('.partial-')), true);
  reject = false;
  const spec = f.schedule[0], result = { ...spec, outcome: 'error', winnerId: null };
  f.store.saveResult(result);
  assert.equal(f.store.results(f.schedule).length, 1);
  assert.throws(() => f.store.saveResult(result), /覆盖/);
  assert.throws(() => f.store.saveResult({ ...result, source: 'controlled' }), /来源/);
  assert.throws(() => f.store.saveResult({ ...result, policyVersion: 'other' }), /版本/);
  assert.throws(() => f.store.saveResult({ ...result, outcome: 'censored', winnerId: 'p0' }), /分类/);
});
test('分段流水：链式摘要/压缩封闭、检查点不含前缀，损坏与不完整尾分别处理', t => {
  const f = fixture(t, { segmentRecords: 2 }), id = f.schedule[0].sampleId;
  f.store.appendAction(id, { type: 'initial', observations: [1] });
  const position = f.store.appendAction(id, { type: 'action', step: 1 });
  f.store.saveCheckpoint(id, { sampleId: id, configHash: f.config.configHash, position, step: 1, stateHash: 'state' });
  assert.equal(f.store.loadEvidence(id).records.length, 2);
  assert.equal(f.store.checkpoint(id).position.records, 2);
  assert.equal(Object.hasOwn(f.store.checkpoint(id), 'actions'), false);
  const directory = path.join(f.store.dir, `samples/${id}/actions`);
  assert.equal(fs.readdirSync(directory).some(n => n.endsWith('.gz')), true);
  f.store.appendAction(id, { type: 'action', step: 2 });
  const active = path.join(directory, 'segment-000001.jsonl');
  fs.appendFileSync(active, '{"incomplete"');
  const evidence = f.store.loadEvidence(id);
  assert.equal(evidence.records.length, 3); assert.equal(evidence.tails.length, 1);
  const restarted = openRun(f.config, { root: f.root, fingerprint, resume: true });
  restarted.appendAction(id, { type: 'action', step: 3 }); restarted.seal(id);
  assert.equal(restarted.loadEvidence(id).records.length, 4);
  assert.equal(fs.readFileSync(active, 'utf8').endsWith('{"incomplete"'), true);
  const gz = path.join(directory, 'segment-000000.jsonl.gz');
  const broken = fs.readFileSync(gz); broken[broken.length - 1] ^= 1; fs.writeFileSync(gz, broken);
  assert.throws(() => restarted.loadEvidence(id), /摘要/);
});
test('输出预算：容量不足不发起写入，原子峰值与原始证据计入占用', t => {
  const f = fixture(t), before = sizeTree(f.store.dir);
  const limited = openRun(f.config, { root: f.root, fingerprint, resume: true, maxBytes: before + 10 });
  assert.equal(limited.bytes, before);
  assert.throws(() => limited.atomic('large.json', { payload: 'x'.repeat(30) }), e => e instanceof StorageStop && e.code === 'output_budget');
  assert.equal(sizeTree(f.store.dir), before);
  assert.equal(fs.existsSync(path.join(f.store.dir, 'large.json')), false);
  assert.equal(limited.remaining(), 10);
});
module.exports = { fixture, fingerprint };
