'use strict';
/* global latestState, game, socket, stockDraft */
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {boot}=require('./helpers/browserHarness'),f=require('../test/helpers/gameplayFixtures');
const {OPPORTUNITIES}=require('../src/gameplayCatalog');
let h;const evidence=[];
test.before(async()=>{h=await boot({viewport:{width:375,height:812}});for(const p of h.pages)await p.evaluate(()=>setInterval(()=>{window.__fixtureRevision=latestState?.revision||0;},10));});
test.after(async()=>{if(h)await h.close();fs.writeFileSync(path.join(__dirname,'../docs/gameplay-usability/browser-evidence/flow.json'),JSON.stringify({node:process.version,prestart:h?.prestart,controlledPreparation:'跨圈、机场归属及旧局为夹具；开局、掷骰、下单、飞行、查询均由真实页面/Socket执行，未运行完整局。',evidence},null,2));});
function origin(s,owner){s.firstRoundDone=true;s.players[0].position=5;s.diceBag=[1];s.airports['开罗国际机场'].ownerId=owner;s.players.find(p=>p.id===owner).airports.push('开罗国际机场');s.airports['伦敦希思罗国际机场'].ownerId='p0';s.players[0].airports.push('伦敦希思罗国际机场');}
async function rules(page){const id=await page.locator('#modal').isVisible()?'btnModalRules':await page.locator('#stockModal').isVisible()?'btnStockRules':'btnRules';await page.click('#'+id);await page.waitForSelector('#rulesModal:not(.hidden)');return id;}
async function go(page){await page.click('#btnRoll');await page.waitForSelector('#stockModal:not(.hidden)');}
async function buy(page,id){await page.locator('button[data-city="'+id+'"][data-kind="buy"][data-delta="1"]').click();await page.click('#btnStockConfirm');await page.waitForFunction(()=>game.phase!=='stock');}
test('手机开局→地图旋转→两次起点→机场明细→只读规则→继续回合',{timeout:60000},async()=>{
 const a=h.pages[0];assert.deepEqual(h.prestart,{lobbyHint:true,roomHint:true});await h.choose();assert.equal(await a.locator('.orientation-hint.ingame').isVisible(),true);
 const s=f.game(2);f.own(s,'p1','上海','东京');s.players[0].name='<甲&乙>';s.firstRoundDone=true;s.players[0].position=41;s.diceBag=[1];await h.fixture(s);
 await a.evaluate(()=>{window.__actions=[];const original=socket.timeout.bind(socket);socket.timeout=ms=>({emit(event,payload,cb){if(event==='action')window.__actions.push(payload);return original(ms).emit(event,payload,cb);}});});
 await go(a);await a.locator('button[data-city="上海"][data-kind="buy"][data-delta="1"]').click();const before=JSON.stringify(h.room.state),draft=await a.evaluate(()=>stockDraft),deadline=h.room.actionClock.deadlineMs;
 await a.setViewportSize({width:812,height:375});await a.waitForTimeout(80);assert.deepEqual(await a.evaluate(()=>stockDraft),draft);assert.equal(JSON.stringify(h.room.state),before);assert.equal(h.room.actionClock.deadlineMs,deadline);
 const piece=await a.evaluate(()=>{const r=document.querySelector('#pieces .piece').getBoundingClientRect(),s=document.querySelector('#board [data-square-id="0"]').getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2,tile:s.toJSON()};});assert.ok(piece.x>=piece.tile.left&&piece.x<=piece.tile.right&&piece.y>=piece.tile.top&&piece.y<=piece.tile.bottom);
 await a.click('#btnStockConfirm');await a.waitForFunction(()=>game.phase!=='stock');assert.equal(h.room.state.players[0].stocks['上海'],1);
 const next=globalThis.structuredClone(h.room.state);next.turnIndex=0;next.turnId++;next.phase='waiting_roll';next.pending=null;next.players[0].position=41;next.diceBag=[1];await h.fixture(next);await go(a);assert.equal(h.room.state.stockWindow.boughtTotal,0);await buy(a,'上海');assert.equal(h.room.state.players[0].stocks['上海'],2);assert.equal(h.room.state.players[0].cash,162000);evidence.push({step:'two-go',shares:2,cash:162000});
 const flight=f.game(2);origin(flight,'p1');await h.fixture(flight);await a.click('#btnRoll');await a.waitForFunction(()=>game.phase==='flight');assert.equal(h.room.state.players[0].cash,147000);const body=await a.textContent('#modalBody');assert.ok(body.includes('已支付通行费：￥3,000'));assert.ok(body.includes('目的机场归属：<甲&乙>')===false);assert.ok(body.includes('目的地属于自己也不会免票'));assert.ok(body.includes('玩家0'));assert.ok(body.includes('实际金额￥5,000'));
 const stateBefore=JSON.stringify(h.room.state),clock=h.room.actionClock.deadlineMs,count=await a.evaluate(()=>window.__actions.length);
 for(const viewport of [{width:1440,height:900},{width:768,height:1024},{width:375,height:812}]){await a.setViewportSize(viewport);const entry=await rules(a);for(const link of await a.locator('.rules-nav a').all()){await link.click();assert.equal(await a.evaluate(()=>document.activeElement.tagName),'SUMMARY');}assert.equal(await a.locator('.rules-opportunity').count(),12);for(const o of OPPORTUNITIES){const text=await a.locator('.rules-opportunity').filter({has:a.getByRole('heading',{name:o.name,exact:true})}).textContent();assert.ok(text.includes(o.description));}await a.click('#btnRulesClose');assert.equal(await a.evaluate(()=>document.activeElement.id),entry);}
 assert.equal(JSON.stringify(h.room.state),stateBefore);assert.equal(h.room.actionClock.deadlineMs,clock);assert.equal(await a.evaluate(()=>window.__actions.length),count);
 await a.getByRole('button',{name:'￥5,000 飞往伦敦希思罗国际机场',exact:true}).click();await a.waitForFunction(()=>game.turnIndex===1);assert.equal(h.room.state.players[0].cash,142000);evidence.push({step:'other-origin-own-destination',toll:3000,ticket:5000,cash:142000});
 const free=f.game(2);origin(free,'p0');f.selected(free,'p0','H7');free.world.active={type:'aviation',name:'航空促销',remaining:3};await h.fixture(free);await a.click('#btnRoll');await a.waitForFunction(()=>game.phase==='flight');assert.ok((await a.textContent('#modalBody')).includes('从自家机场出发，机票免费'));await a.getByRole('button',{name:'￥0 飞往伦敦希思罗国际机场',exact:true}).click();await a.waitForFunction(()=>game.turnIndex===1);assert.equal(h.room.state.players[0].cash,150000);assert.equal(h.room.state.players[0].opportunities.usage.H7||0,0);evidence.push({step:'own-origin',cash:150000});
 const missing=f.game(2);missing.phase='flight';missing.pending={playerId:'p0',fromAirportId:'开罗国际机场',free:false};await h.fixture(missing);assert.ok((await a.textContent('#modalBody')).includes('本次资料未提供'));await rules(a);h.api.runAction(h.room,null,{type:'flight',target:null},'timeout');await a.waitForFunction(()=>game.turnIndex===1);await a.click('#btnRulesClose');assert.equal(await a.locator('#modal').isVisible(),false);
 const special=f.game(2);f.own(special,'p0','上海');special.players[0].name='<甲&乙>';await h.fixture(special);assert.ok((await a.textContent('#sidePlayer')).includes('<甲&乙>'));await a.locator('#board [data-square-id="36"]').click();assert.ok((await a.textContent('#modalBody')).includes('<甲&乙>'));assert.equal(await a.locator('#sidePlayer 甲').count(),0);await a.getByRole('button',{name:'关闭',exact:true}).last().click();await rules(a);assert.ok((await a.textContent('#rulesBody')).includes('当前适用原经济规则，无新增回合开支'));await a.click('#btnRulesClose');
 const old=f.game(2,1);old.gameId=h.room.state.gameId;old.revision=h.room.state.revision+1;for(const [i,p]of old.players.entries())p.socketId=h.room.players[i].socketId;h.room.state=old;h.api.emitGame(h.room);await a.waitForFunction(t=>game.startedAt===t&&game.ruleVersion!==2,old.startedAt);await rules(a);assert.equal(await a.locator('.rules-opportunity').count(),0);assert.ok((await a.textContent('#rules-topic-stocks')).includes('历史股票规则'));await a.click('#btnRulesClose');
 assert.deepEqual(h.errors,[]);evidence.push({step:'rules',topics:8,catalogue:12,readOnly:true,specialName:true,legacy:true,browserErrors:h.errors});
});
